package main.java.com.wonen.veterinaria.views.comun;

public enum TipoMascaraTextField {
    TODO, TELEFONO, CORREO, SOLO_NUMEROS_ENTEROS, SOLO_NUMEROS_DECIMALES, SOLO_LETRAS, SOLO_LETRAS_MAYUSC, SOLO_LETRAS_MINUSC, NUMEROS_Y_LETRAS, NUMEROS_Y_LETRAS_MAYUSC, NUMEROS_Y_LETRAS_MINUSC;
}
